[project]
site_name = "Nave"
site_url = "https://lmmx.github.io/nave
site_description = "nave: fleet-level ops for OSS repos"
site_author = "Louis Maddox"

docs_dir = "docs"

repo_name = "lmmx/nave"
repo_url = "https://github.com/lmmx/nave"

# Navigation
nav = [
  { "Home" = "index.md" }
]

[project.theme]
variant = "modern"
language = "en"

features = [
  "navigation.instant",
  "navigation.top",
  "search.suggest",
  "search.highlight",
  "content.code.copy"
]

# Light / dark mode toggle
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"

[project.plugins.search]